name: "Dub Upgrade"
description: "Run `dub upgrade` trying to repeat on network failure and using package cache"
author: "WebFreak001"
branding:
  icon: "package"
  color: "red"
inputs:
  cache:
    description: "Boolean if packages should be cached. Downloaded packages are restored before the build and saved automatically at the end of the job via the post step."
    default: 'true'
  args:
    description: "Any custom arguments (shell syntax) to pass after `dub upgrade`. Will be used multiple times in case of dub network failures."
    default: "--missing-only --sub-packages"
runs:
  using: "node24"
  main: "lib/main.js"
  post: "lib/post.js"
  post-if: "always()"
