name: "Dub Upgrade"
description: "Run `dub upgrade` trying to repeat on network failure and using package cache"
author: "WebFreak001"
inputs:
  cache:
    description: "Boolean if packages should be cached. If this is called before a build this will only cache downloaded files, if this is called after a build as well this will cache the compiled libraries, making future completion faster."
    default: true
  args:
    description: "Any custom arguments (shell syntax) to pass after `dub upgrade`. Will be used multiple times in case of dub network failures."
    default: ""
runs:
  using: "node12"
  main: "lib/main.js"
