name: Test dub upgrade functionality
on:
  push:
    branches:
    - "master"
    - "release"
  pull_request:
    branches:
    - "*"

jobs:
  run:
    name: Test Action
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dc: [ldc-latest, dmd-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Install action dependencies
        if: (! startsWith(github.ref, 'v'))
        run: npm install --production

      - name: Dub Upgrade
        uses: ./
        with:
          args: "--root test"

